  version: '3.3'
  services:
    postgres:
      image: postgres:latest
      network_mode: bridge
      container_name: postgres
      volumes:
        - "dbbanquedata:/var/lib/postgresql/data"
      expose:
        - 5432
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
    # APP*****************************************
    API:
      image: banque_api:latest
      network_mode: bridge
      container_name: banque_api
      build:
        context: ./
        dockerfile: Dockerfile
      expose:
        - 8080
      ports:
        - "8080:8080"
      restart: unless-stopped
      depends_on:
        - postgres
      links:
        - postgres
    COMMERCANT_API:
      image: commerce_api:latest
      network_mode: bridge
      container_name: commerce_api
      build:
        context: ./
        dockerfile: Dockerfile_commerce
      expose:
        - 8082
      ports:
        - "8082:8082"
      restart: unless-stopped
    
  volumes:
    dbbanquedata:
