FROM maven:3-openjdk-11 AS BUILDER
WORKDIR /app
COPY ./gateway-service .
RUN mvn -e -B -DskipTests clean package

FROM openjdk:11
COPY --from=BUILDER /app/target/gateway-service-1.0.jar .
EXPOSE 8080
CMD ["java","-jar","gateway-service-1.0.jar"]