FROM maven:3-openjdk-11 AS BUILDER
WORKDIR /app
COPY ./CommerceApi .
RUN mvn -e -B -DskipTests clean package

FROM openjdk:11
COPY --from=BUILDER /app/target/revolutcommercemiage-0.0.1-SNAPSHOT.jar .
EXPOSE 8082
CMD ["java","-jar","revolutcommercemiage-0.0.1-SNAPSHOT.jar"]